loki:
  persistence:
    enabled: true
    storageClassName: nfs-storage
    size: 10Gi

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki:3100/loki/api/v1/push
